// Real React preview plus browser interaction checks; all data is synthetic.
import { readFileSync } from 'node:fs'
import { createServer } from 'node:http'
import { resolve } from 'node:path'
import { build } from 'esbuild'
import { sanitizeConfig } from '../lib/store.js'
const root = resolve(import.meta.dirname, '..')
const source = readFileSync(resolve(root, 'src/statistics/index.js'), 'utf8')
const entry = `import React from 'react';import{createRoot}from'react-dom/client';
let factory;window.__ModuleLoader__={load:m=>factory=m.factory};${source}
const ui=factory(()=>React),params=new URLSearchParams(location.search),locale=params.get('locale')||'zh';
const bucket={input:39001,output:51899,cacheRead:1275904,cacheWrite:0,reasoning:0,calls:28,cost:0.2722,apiCost:0.2722};
const costRows=[['input',39001,1],['output',51899,4],['cacheRead',1275904,.02]].map(([bucket,tokens,rate])=>({provider:'deepseek',model:'deepseek-v4-flash',bucket,tokens,rate,cost:tokens*rate/1e6,priced:true,plan:false}));
const calls=Array.from({length:28},(_,i)=>({kind:i<26?'model':'search',turn:i<26?2:null,step:i<26?i+1:null,provider:'deepseek',model:'deepseek-v4-flash',atMs:1790762400000+i*10000,cost:bucket.cost/28,apiCost:bucket.cost/28,plan:false,priced:true,longContext:false,rows:costRows}));
const turns=[{...bucket,turn:1,cost:.00597,apiCost:.00597,calls:1},{...bucket,turn:2,cost:.26623,apiCost:.26623,calls:27}];
const shares=Array.from({length:8},(_,i)=>({...bucket,turn:2,step:i+1,other:false,unpriced:false,cost:bucket.cost*(8-i)/36,apiCost:bucket.cost*(8-i)/36,calls:i+1}));
const detail={found:true,...bucket,rows:costRows,calls,totalCalls:28,offset:0,recorded:bucket,kinds:[{...bucket,kind:'model',calls:26,unpriced:false},{...bucket,kind:'search',calls:2,unpriced:false}],turns,totalTurns:2,turnOffset:0,stepShares:{cost:shares,calls:shares.map((s,i)=>({...s,calls:i===7?0:i+1}))}};
const inspection={found:true,turn:2,input:locale==='zh'?'做一个简单的网页，增加夜间模式，并确认窄窗口中的内容没有溢出。':'Build a simple website with dark mode and verify its layout in a narrow window.',inputTruncated:false,tools:[{seq:1,step:1,name:'read_file',callId:'c1',atMs:1790762400000,arguments:JSON.stringify({path:'src/index.html'},null,2),result:'<main>Welcome</main>',status:'complete',truncated:false},{seq:2,step:2,name:'exec_command',callId:'c2',atMs:1790762400000,arguments:JSON.stringify({command:'npm run build'},null,2),result:'Build completed successfully. 28 modules transformed.',status:'complete',truncated:false}],offset:0,totalTools:2};
const api={getBillingStatistics:async()=>({from:'2026-09-24',to:'2026-09-30',retainedFrom:'2026-08-14',retainedTo:'2026-09-30',totals:bucket,days:Array.from({length:7},(_,i)=>({...bucket,date:'2026-09-'+(24+i),cost:bucket.cost*(i+1)/28,apiCost:bucket.cost*(i+1)/28})),models:[{...bucket,key:'deepseek:deepseek-v4-flash',provider:'deepseek',model:'deepseek-v4-flash',priced:true}],sessions:[{...bucket,id:'s',title:locale==='zh'?'做一个简单的网页':'Build a simple website'}],providers:['deepseek'],modelOptions:['deepseek-v4-flash'],sessionCount:1,offset:0,unassignedCost:0,unmodeledCost:0}),getSessionBilling:async()=>detail,getTurnInspection:async q=>({...inspection,turn:q.turn})};
createRoot(document.getElementById('root')).render(React.createElement(ui.Statistics,{state:{config:{...${JSON.stringify(sanitizeConfig({}))},locale},meta:{dayKey:'2026-09-30',timezone:'Asia/Shanghai',now:1}},api,sessionId:'s',formatMoneyUsd:n=>'¥'+n.toFixed(n&&n<.01?6:4),formatTokens:n=>n>1000?(n/1000).toFixed(1)+'K':String(n)}));`
const bundle = await build({ stdin: { contents: entry, loader: 'js', resolveDir: root }, bundle: true, write: false, nodePaths: [resolve(process.argv[2])], format: 'iife', define: { 'process.env.NODE_ENV': '"production"' } })
const cases = [360, 768, 1100].flatMap(width => ['zh', 'en'].flatMap(locale => ['light', 'dark'].map(theme => ({ width, locale, theme }))))
const page = `<!doctype html><meta charset="utf-8"><title>Statistics UI regression</title><style>body{font:14px system-ui}iframe{height:720px;border:1px solid #ddd}section{margin:20px}</style><h1>Statistics UI · synthetic fixtures</h1><button id="run">Run regression</button><p role="status" id="result">Ready</p>${cases.map(c=>`<section>${c.width} ${c.locale} ${c.theme}<br><iframe title="${c.width}-${c.locale}-${c.theme}" width="${c.width}" src="/case?locale=${c.locale}&theme=${c.theme}"></iframe></section>`).join('')}
<script>document.getElementById('run').onclick=async()=>{let count=0;const check=(v,m)=>{count++;if(!v)throw Error(m)},wait=()=>new Promise(r=>setTimeout(r,50));try{for(const f of document.querySelectorAll('iframe')){const d=f.contentDocument,w=f.contentWindow;check(d.documentElement.scrollWidth<=w.innerWidth,f.title+' no page overflow');check(d.querySelectorAll('.cm-stat-metric').length===4,f.title+' four metrics');check(d.querySelectorAll('.cm-stat-share-list').length===3,f.title+' composition, types and all-step shares');check(!d.querySelector('.cm-stat-inspection'),f.title+' inspection stays lazy');d.querySelector('.cm-stat-turn-toggle').click();await wait();check(!!d.querySelector('.cm-stat-inspection'),f.title+' turn opens');check(d.querySelector('.cm-stat-pre').textContent.length>10,f.title+' user input');const tool=d.querySelector('.cm-stat-tool');tool.open=true;check(tool.textContent.includes('src/index.html'),f.title+' tool arguments');check(tool.textContent.includes('<main>Welcome</main>'),f.title+' escaped tool result');check(!tool.querySelector('main'),f.title+' result is never interpreted as HTML');d.querySelector('.cm-stat-turn-toggle').click();await wait();check(!d.querySelector('.cm-stat-inspection'),f.title+' turn closes');check(d.documentElement.scrollWidth<=w.innerWidth,f.title+' still no page overflow');}document.getElementById('result').textContent='PASS '+count+' assertions';}catch(e){document.getElementById('result').textContent='FAIL '+count+' '+e.message;}}</script>`
const server = createServer((request, response) => {
  if (request.url === '/entry.js') { response.setHeader('content-type', 'text/javascript; charset=utf-8'); response.end(bundle.outputFiles[0].text); return }
  response.setHeader('content-type','text/html; charset=utf-8')
  const dark = request.url.includes('theme=dark')
  response.end(request.url.startsWith('/case') ? `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>:root{color-scheme:${dark?'dark':'light'};--dsw-alias-label-primary:${dark?'#ececef':'#25262b'};--dsw-alias-label-tertiary:${dark?'#9597a1':'#858a94'};--dsw-alias-bg-base:${dark?'#202124':'#fff'};--dsw-alias-bg-layer-1:${dark?'#27282d':'#f7f8fa'};--dsw-alias-bg-layer-2:${dark?'#292b30':'#f5f6f8'};--dsw-alias-border-l1:${dark?'#35373e':'#eceef0'};--dsw-alias-border-l3:${dark?'#35373e':'#e9eaed'};--dsw-alias-state-business-primary:${dark?'#8096ff':'#4d6bfe'};--dsw-alias-interactive-bg-hover:${dark?'#32343a':'#eff0f3'};--ds-font-family-sans:Arial,'Microsoft YaHei',sans-serif}body{margin:0;background:var(--dsw-alias-bg-base);font-family:var(--ds-font-family-sans)}#root{padding:24px;max-width:1160px;margin:auto;box-sizing:border-box}@media(max-width:600px){#root{padding:14px}}</style><div id="root"></div><script src="/entry.js"></script>` : page)
})
server.listen(0, '127.0.0.1', () => console.log('http://127.0.0.1:' + server.address().port))
